services:
  - type: web
    name: your-service-name
    env: python
    plan: free
    pythonVersion: 3.11.7
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run your_app.py
